openapi: 3.2.0
info:
  title: FSC Core Contracts API
  version: 1.0.0
  description: Manager REST API
servers:
- url: https://{managerUrl}:8443/v1
  variables:
    managerUrl:
      default: localhost
      description: URL of the Manager
tags:
- name: Contracts
paths:
  /contracts:
    post:
      operationId: submitContract
      summary: Submit a new contract
      parameters:
      - $ref: '#/components/parameters/headerFscManagerAddress'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  $ref: '#/components/schemas/contractContent'
                signature:
                  description: An accept signature of the Peer submitting the contract
                  type: string
              required:
              - content
              - signature
      responses:
        201:
          description: Contract created
        422:
          description: Unprocessable content
          headers:
            Fsc-Error-Code:
              $ref: '#/components/headers/FscErrorCode'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                peerNotPartOfContract:
                  $ref: '#/components/examples/peerNotPartOfContract'
                grantCombinationNotAllowed:
                  $ref: '#/components/examples/grantCombinationNotAllowed'
                signatureContentMismatch:
                  $ref: '#/components/examples/signatureContentMismatch'
                peerIDSignatureMismatch:
                  $ref: '#/components/examples/peerIDSignatureMismatch'
                signatureVerificationFailed:
                  $ref: '#/components/examples/signatureVerificationFailed'
        400:
          description: Bad request
          headers:
            Fsc-Error-Code:
              $ref: '#/components/headers/FscErrorCode'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                peerCertificateVerificationFailed:
                  $ref: '#/components/examples/peerCertificateVerificationFailed'
      tags:
      - Contracts
    get:
      summary: Returns Contracts sorted by their creation date
      parameters:
      - $ref: '#/components/parameters/queryPaginationCursor'
      - $ref: '#/components/parameters/queryPaginationLimit'
      - $ref: '#/components/parameters/queryPaginationOrder'
      - in: query
        description: A Grant type on which to filter. Returns Contracts which contain a Grant of the Grant Type specified in the grant_type filter
        name: grant_type
        schema:
          $ref: '#/components/schemas/grantType'
        required: false
        style: form
        explode: false
      - in: query
        description: A list of Grant hashes on which to filter. Returns Contracts that contain a Grant with the same Grant hash as specified in the grant_hash filter.  When this query parameter is set the pagination parameters and the GrantType filter should be ignored
        name: grant_hash
        schema:
          type: array
          items:
            type: string
            description: The hash of a Grant
            example: $1$4$-PQI7we01qIfEwq4O5UioLKzjGBgRva6F5-bUfDlKxUjcY5yX1MRsn6NKquDbL8VcklhYO9sk18rHD6La3w_mg
            maxLength: 1024
        required: false
        style: form
        explode: false
      responses:
        200:
          description: Contracts
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    description: List of Contracts
                    type: array
                    items:
                      $ref: '#/components/schemas/contract'
                  pagination:
                    $ref: '#/components/schemas/paginationResult'
                required:
                - contracts
                - pagination
      tags:
      - Contracts
      operationId: getContracts
      x-operation-id-source: derived
  /contracts/{hash}/accept:
    put:
      summary: Accept contract
      operationId: acceptContract
      parameters:
      - $ref: '#/components/parameters/headerFscManagerAddress'
      - $ref: '#/components/parameters/pathContractContentHash'
      requestBody:
        $ref: '#/components/requestBodies/signatureRequest'
      responses:
        201:
          description: Signature created
        422:
          description: Unprocessable content
          headers:
            Fsc-Error-Code:
              $ref: '#/components/headers/FscErrorCode'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                signatureContentMismatch:
                  $ref: '#/components/examples/signatureContentMismatch'
                peerIDSignatureMismatch:
                  $ref: '#/components/examples/peerIDSignatureMismatch'
                signatureVerificationFailed:
                  $ref: '#/components/examples/signatureVerificationFailed'
        400:
          description: Bad request
          headers:
            Fsc-Error-Code:
              $ref: '#/components/headers/FscErrorCode'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                peerCertificateVerificationFailed:
                  $ref: '#/components/examples/peerCertificateVerificationFailed'
      tags:
      - Contracts
components:
  schemas:
    service:
      description: The details of a Service
      type: object
      properties:
        type:
          $ref: '#/components/schemas/serviceType'
        peer_id:
          $ref: '#/components/schemas/peerID'
        name:
          $ref: '#/components/schemas/serviceName'
      required:
      - type
      - peer_id
      - name
    error:
      type: object
      properties:
        message:
          description: A message describing the error
          type: string
        domain:
          $ref: '#/components/schemas/errorDomain'
        code:
          $ref: '#/components/schemas/errorCode'
      required:
      - message
      - domain
      - code
    validity:
      type: object
      properties:
        not_before:
          description: A Unix timestamp, the Contract is not valid before this date.
          type: integer
          format: int64
          example: 1672527600
          minimum: 0
        not_after:
          description: A Unix timestamp, the Contract is not valid after this date.
          type: integer
          format: int64
          example: 1704063600
          minimum: 0
      required:
      - not_before
      - not_after
    grantDelegatedServicePublication:
      description: A DelegatedServicePublicationGrant
      type: object
      properties:
        type:
          $ref: '#/components/schemas/grantType'
        directory:
          $ref: '#/components/schemas/directory'
        service:
          $ref: '#/components/schemas/servicePublication'
        delegator:
          $ref: '#/components/schemas/delegator'
        properties:
          description: Optional JSON object with arbitrary key-value pairs
          additionalProperties: true
          type: object
      required:
      - type
      - directory
      - service
      - delegator
    inwayErrorsCode:
      description: Error reasons that can be produced by the Inway
      type: string
      enum:
      - ERROR_CODE_ACCESS_TOKEN_MISSING
      - ERROR_CODE_ACCESS_TOKEN_INVALID
      - ERROR_CODE_ACCESS_TOKEN_EXPIRED
      - ERROR_CODE_SERVICE_NOT_FOUND
      - ERROR_CODE_SERVICE_UNREACHABLE
      - ERROR_CODE_WRONG_GROUP_ID_IN_TOKEN
    hashAlgorithm:
      description: The hashing algorithm
      type: string
      enum:
      - HASH_ALGORITHM_SHA3_512
    delegatedService:
      description: The details of a Service that is offered on behalf of another Peer
      type: object
      properties:
        type:
          $ref: '#/components/schemas/serviceType'
        peer_id:
          $ref: '#/components/schemas/peerID'
        name:
          $ref: '#/components/schemas/serviceName'
        delegator:
          $ref: '#/components/schemas/delegator'
      required:
      - type
      - peer_id
      - name
      - delegator
    errorCode:
      description: A unique code specifying the error
      type: string
      oneOf:
      - $ref: '#/components/schemas/inwayErrorsCode'
      - $ref: '#/components/schemas/outwayErrorCode'
      - $ref: '#/components/schemas/managerErrorCode'
    grantDelegatedServiceConnection:
      description: A DelegatedServiceConnectionGrant
      type: object
      properties:
        type:
          $ref: '#/components/schemas/grantType'
        outway:
          $ref: '#/components/schemas/outway'
        service:
          oneOf:
          - $ref: '#/components/schemas/service'
          - $ref: '#/components/schemas/delegatedService'
          discriminator:
            propertyName: type
            mapping:
              SERVICE_TYPE_SERVICE: '#/components/schemas/service'
              SERVICE_TYPE_DELEGATED_SERVICE: '#/components/schemas/delegatedService'
        delegator:
          $ref: '#/components/schemas/delegator'
        properties:
          description: Optional JSON object with arbitrary key-value pairs
          additionalProperties: true
          type: object
      required:
      - type
      - outway
      - service
      - delegator
    outwayIdentificationDomainName:
      description: The details of the Outway based on a domain name for which a connection was authorized
      type: object
      properties:
        type:
          $ref: '#/components/schemas/outwayIdentificationType'
        domain_name:
          $ref: '#/components/schemas/domainName'
      required:
      - type
      - domain_name
    outwayErrorCode:
      description: Error reasons that can be produced by the Outway
      type: string
      enum:
      - ERROR_CODE_METHOD_UNSUPPORTED
    serviceName:
      description: The name of a service
      type: string
      example: random_service_name
      minLength: 3
      maxLength: 255
    sortOrder:
      description: The order in which the results should be returned
      type: string
      default: SORT_ORDER_DESCENDING
      enum:
      - SORT_ORDER_ASCENDING
      - SORT_ORDER_DESCENDING
    outwayIdentificationType:
      description: The type of Outway identification
      type: string
      enum:
      - OUTWAY_IDENTIFICATION_TYPE_PUBLIC_KEY_THUMBPRINT
      - OUTWAY_IDENTIFICATION_TYPE_DOMAIN_NAME
    grantServicePublication:
      description: A ServicePublicationGrant
      type: object
      properties:
        type:
          $ref: '#/components/schemas/grantType'
        directory:
          $ref: '#/components/schemas/directory'
        service:
          $ref: '#/components/schemas/servicePublication'
        properties:
          description: Optional JSON object with arbitrary key-value pairs
          additionalProperties: true
          type: object
      required:
      - type
      - directory
      - service
    signatureMap:
      description: Map of PeerIDs and accept signatures
      type: object
      additionalProperties:
        description: signature
        type: string
      example:
        '12345678901234567891': eyJhbGciOiJSUzUxMiIsIng1dCNTMjU2IjoiRzRYNEM0bmFXZmRERG5qSi9aV2RzNGFPcWhzVTZnUklPNlQxM1pMNEsyST0ifQ.eyJjb250ZW50SGFzaCI6IiQxJDEkWmFxbiszaWFoM2FkMmtuYjJKc2JhR2g2bi9rZ1UrUWpVK0pmTmhuVkdCd1RGbnN1TUNjOUlRcHlPM0xabmt0WUtaWWh4TnpKalh5RWlLMnVWZTZEZ3c9PSIsInR5cGUiOiJhY2NlcHQifQ.Qs7M3EBVWbrzhjPioDhbhNP8BJQqkxPOPq-Pm6oWL_ZO9m74TIeUHk1gQ1QcqZs_zGALjmDLuOSLLEgz3Qh4iK5jadex14z-i3xJObb5vcjVN326CxdJNzRZo60c9KWY4Nrh7ewziXJv8BQ3x4se62p5paCKdN8quWiG9J5gN4F5dmtZyae0rEhQsy-fy5ugLHPhR97cschr8OnlStVQKRYcUqn7obCnKLNOv-L9a02umsw6ha-G8CSMr3z9QZMfYcPABQAaR3XamUIR_T-ZGiZbpuTDaLfqztCP9jrZ7Q6g4J6SmQtxkcbzj4YdXXcwOr9aUO-07LZuH__tHGXU2bzgsObiClP5Fx13VT0zJzM5rdMtS5OnRwvznIFJUG1VkXXIRG9pVpffOM-kO-FsFW6BTWGi5nBJfi21nLUTh-bNVPB9O8WVfVBl8PwZ2HzjNy0asI_6I2jpweRh8-KNLM5ca18YS1VUS8cgfnc7qFcrnI8kxxDqyITOd2-LMRsngvmJpoJkmKjNIHbnJaoXdvMqFss7YHitJQi7wz3VUKLojK8XdaUc40KQtx7VIdBX9ClDdUFY1kXPxM_c0zLGsLn60a-4PLtUBZEPnBgxZd7-9st9ivBkPXylG9ZNqIe6aD4qxBtp91vI2w18X-MmYT-wb73PcF2IySAuzFk-uqI
    publicKeyThumbprint:
      description: The SHA-256 thumbprint of the public key used in the certificate of the Outway in HEX-encoded format
      type: string
      example: 3a56f2e9269ac63f0d4394c46b96539da1625b6a985d38029ff89f34e490960c
      maxLength: 64
      minLength: 64
    paginationResult:
      type: object
      properties:
        next_cursor:
          description: A cursor that can be used to retrieve the next page or an empty string if there are no more results
          type: string
    protocol:
      description: application layer protocol supported
      type: string
      enum:
      - PROTOCOL_TCP_HTTP_1.1
      - PROTOCOL_TCP_HTTP_2
    serviceType:
      description: The type of Service
      type: string
      enum:
      - SERVICE_TYPE_SERVICE
      - SERVICE_TYPE_DELEGATED_SERVICE
    grant:
      description: A Grant
      type: object
      required:
      - data
      properties:
        data:
          description: The details of the Grant
          oneOf:
          - $ref: '#/components/schemas/grantServicePublication'
          - $ref: '#/components/schemas/grantServiceConnection'
          - $ref: '#/components/schemas/grantDelegatedServiceConnection'
          - $ref: '#/components/schemas/grantDelegatedServicePublication'
          discriminator:
            propertyName: type
            mapping:
              GRANT_TYPE_SERVICE_PUBLICATION: '#/components/schemas/grantServicePublication'
              GRANT_TYPE_SERVICE_CONNECTION: '#/components/schemas/grantServiceConnection'
              GRANT_TYPE_DELEGATED_SERVICE_CONNECTION: '#/components/schemas/grantDelegatedServiceConnection'
              GRANT_TYPE_DELEGATED_SERVICE_PUBLICATION: '#/components/schemas/grantDelegatedServicePublication'
    outway:
      type: object
      properties:
        peer_id:
          $ref: '#/components/schemas/peerID'
        identification:
          oneOf:
          - $ref: '#/components/schemas/outwayIdentificationDomainName'
          - $ref: '#/components/schemas/outwayIdentificationPublicKeyThumbprint'
          discriminator:
            propertyName: type
            mapping:
              OUTWAY_IDENTIFICATION_TYPE_PUBLIC_KEY_THUMBPRINT: '#/components/schemas/outwayIdentificationPublicKeyThumbprint'
              OUTWAY_IDENTIFICATION_TYPE_DOMAIN_NAME: '#/components/schemas/outwayIdentificationDomainName'
      required:
      - peer_id
      - identification
    contract:
      description: A Contract
      type: object
      properties:
        content:
          $ref: '#/components/schemas/contractContent'
        signatures:
          $ref: '#/components/schemas/signatures'
      required:
      - content
      - signatures
    managerErrorCode:
      description: Error reasons that can be produced by the Manager
      type: string
      enum:
      - ERROR_CODE_INCORRECT_GROUP_ID
      - ERROR_CODE_PEER_NOT_PART_OF_CONTRACT
      - ERROR_CODE_SIGNATURE_CONTRACT_CONTENT_HASH_MISMATCH
      - ERROR_CODE_PEER_CERTIFICATE_VERIFICATION_FAILED
      - ERROR_CODE_PEER_ID_SIGNATURE_MISMATCH
      - ERROR_CODE_SIGNATURE_VERIFICATION_FAILED
      - ERROR_CODE_GRANT_COMBINATION_NOT_ALLOWED
      - ERROR_CODE_URL_PATH_CONTENT_HASH_MISMATCH
      - ERROR_CODE_UNKNOWN_HASH_ALGORITHM_HASH
      - ERROR_CODE_UNKNOWN_ALGORITHM_SIGNATURE
      - ERROR_CODE_INCORRECT_PUBLIC_KEY_THUMBPRINT
    directory:
      description: The details of the Directory
      type: object
      properties:
        peer_id:
          $ref: '#/components/schemas/peerID'
      required:
      - peer_id
    grantServiceConnection:
      description: A ServiceConnectionGrant
      type: object
      properties:
        type:
          $ref: '#/components/schemas/grantType'
        outway:
          $ref: '#/components/schemas/outway'
        service:
          oneOf:
          - $ref: '#/components/schemas/service'
          - $ref: '#/components/schemas/delegatedService'
          discriminator:
            propertyName: type
            mapping:
              SERVICE_TYPE_SERVICE: '#/components/schemas/service'
              SERVICE_TYPE_DELEGATED_SERVICE: '#/components/schemas/delegatedService'
        properties:
          description: Optional JSON object with arbitrary key-value pairs
          additionalProperties: true
          type: object
      required:
      - type
      - outway
      - service
    signatures:
      type: object
      description: The accept, reject and revoke signatures
      properties:
        accept:
          $ref: '#/components/schemas/signatureMap'
        reject:
          $ref: '#/components/schemas/signatureMap'
        revoke:
          $ref: '#/components/schemas/signatureMap'
      required:
      - accept
      - reject
      - revoke
    errorDomain:
      description: The FSC component in which the error occurred
      type: string
      enum:
      - ERROR_DOMAIN_INWAY
      - ERROR_DOMAIN_OUTWAY
      - ERROR_DOMAIN_MANAGER
    delegator:
      description: The details of a Delegator
      type: object
      properties:
        peer_id:
          $ref: '#/components/schemas/peerID'
      required:
      - peer_id
    servicePublication:
      description: The details of a Service publication
      type: object
      properties:
        peer_id:
          $ref: '#/components/schemas/peerID'
        name:
          $ref: '#/components/schemas/serviceName'
        protocol:
          $ref: '#/components/schemas/protocol'
      required:
      - name
      - peer_id
      - protocol
    grantType:
      description: The type of Grant
      type: string
      enum:
      - GRANT_TYPE_SERVICE_PUBLICATION
      - GRANT_TYPE_SERVICE_CONNECTION
      - GRANT_TYPE_DELEGATED_SERVICE_CONNECTION
      - GRANT_TYPE_DELEGATED_SERVICE_PUBLICATION
    peerID:
      description: The ID of a Peer
      type: string
      example: '12345678901234567891'
      minLength: 3
      maxLength: 255
    contractContent:
      description: The content of a Contract
      type: object
      properties:
        fsc_version:
          description: The version of the FSC specification that the Contract adheres to.
          type: string
          example: 1.0.0
        iv:
          description: An Initialization vector for the Contract. Must be an UUID.
          type: string
          example: 06338364-8305-7b74-8000-de4963503139
          minLength: 36
          maxLength: 36
        group_id:
          description: The FSC Group ID
          type: string
          example: example.fsc.com
        validity:
          $ref: '#/components/schemas/validity'
        grants:
          description: The Grants of the Contract
          type: array
          items:
            $ref: '#/components/schemas/grant'
        hash_algorithm:
          $ref: '#/components/schemas/hashAlgorithm'
        created_at:
          description: A Unix timestamp of the creation date of the Contract
          type: integer
          format: int64
          example: 1672527600
          minimum: 0
      required:
      - fsc_version
      - iv
      - group_id
      - validity
      - grants
      - hash_algorithm
      - created_at
    outwayIdentificationPublicKeyThumbprint:
      description: The details of the Outway based on a public key thumbprint for which a connection was authorized
      type: object
      properties:
        type:
          $ref: '#/components/schemas/outwayIdentificationType'
        public_key_thumbprint:
          $ref: '#/components/schemas/publicKeyThumbprint'
      required:
      - type
      - public_key_thumbprint
    domainName:
      description: A domain name according to RFC 1035
      type: string
      minLength: 1
      maxLength: 255
      example: example.com
  examples:
    signatureContentMismatch:
      summary: Signature Contract content mismatch
      value:
        code: ERROR_CODE_SIGNATURE_CONTRACT_CONTENT_HASH_MISMATCH
        message: signature contract content hash '$1$1$ouqPHvHP9-ZDKo4YDNz4GGYENOQQ80knSVg6lJ_MjaTLE_o3GgD1Vzyzteu791X0rkX6FvlJzyBYdZuD6hlWrQ' does not match the contract content hash '$1$1$rrvHPvHP9-ZDKo4YDNz4GGYENOQQ80knSVg6lJ_MjaTLE_o3GgD1Vzyzteu791X0rkX6FvlJzyBYdZuD6hlrfL'
        domain: ERROR_DOMAIN_MANAGER
    peerCertificateVerificationFailed:
      summary: Peer certificate verification failed
      value:
        code: ERROR_CODE_PEER_CERTIFICATE_VERIFICATION_FAILED
        message: the peer id '0001' is in a incorrect format
        domain: ERROR_DOMAIN_MANAGER
    peerIDSignatureMismatch:
      summary: Peer ID does not match signature
      value:
        code: ERROR_CODE_PEER_ID_SIGNATURE_MISMATCH
        message: peer id '0001' does not match signature peer id '0002'
        domain: ERROR_DOMAIN_MANAGER
    grantCombinationNotAllowed:
      summary: Grant combination not allowed
      value:
        code: ERROR_CODE_GRANT_COMBINATION_NOT_ALLOWED
        message: cannot combine a service publication grant with any other grant type
        domain: ERROR_DOMAIN_MANAGER
    peerNotPartOfContract:
      summary: Peer not part of the Contract
      value:
        code: ERROR_CODE_PEER_NOT_PART_OF_CONTRACT
        message: peer '0001' not part of the contract
        domain: ERROR_DOMAIN_MANAGER
    signatureVerificationFailed:
      summary: Signature verification failed
      value:
        code: ERROR_CODE_SIGNATURE_VERIFICATION_FAILED
        message: unable to retrieve certificate with thumbprint 'h_CeVoeJ5vdaFGzNYPqiKWnGtDKB9UvIa_uk5Yvm7gs' from manager of peer '0001'
        domain: ERROR_DOMAIN_MANAGER
  headers:
    FscErrorCode:
      schema:
        $ref: '#/components/schemas/errorCode'
      required: true
  parameters:
    queryPaginationCursor:
      in: query
      name: cursor
      description: A cursor from which paginated results should be returned. Leave empty for the first page
      schema:
        type: string
      required: false
    pathContractContentHash:
      in: path
      name: hash
      description: The hash of the Contract content
      schema:
        type: string
        example: $1$1$ouqPHvHP9-ZDKo4YDNz4GGYENOQQ80knSVg6lJ_MjaTLE_o3GgD1Vzyzteu791X0rkX6FvlJzyBYdZuD6hlWrQ
      required: true
    queryPaginationOrder:
      in: query
      name: sort_order
      description: The sorting order of the results
      required: false
      schema:
        $ref: '#/components/schemas/sortOrder'
    headerFscManagerAddress:
      in: header
      name: fsc-manager-address
      description: The URL of the Manager. The scheme must be https and the URL must contain the port.
      schema:
        type: string
        example: https://manager.com:8443
      required: true
    queryPaginationLimit:
      in: query
      name: limit
      description: The maximum number of results
      schema:
        type: integer
        format: uint32
        maximum: 1000
        minimum: 1
      required: false
  requestBodies:
    signatureRequest:
      description: A signature request
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                $ref: '#/components/schemas/contractContent'
              signature:
                description: The signature
                type: string
                example: eyJhbGciOiJSUzUxMiIsIng1dCNTMjU2IjoiRzRYNEM0bmFXZmRERG5qSi9aV2RzNGFPcWhzVTZnUklPNlQxM1pMNEsyST0ifQ.eyJjb250ZW50SGFzaCI6IiQxJDEkWmFxbiszaWFoM2FkMmtuYjJKc2JhR2g2bi9rZ1UrUWpVK0pmTmhuVkdCd1RGbnN1TUNjOUlRcHlPM0xabmt0WUtaWWh4TnpKalh5RWlLMnVWZTZEZ3c9PSIsInR5cGUiOiJhY2NlcHQifQ.Qs7M3EBVWbrzhjPioDhbhNP8BJQqkxPOPq-Pm6oWL_ZO9m74TIeUHk1gQ1QcqZs_zGALjmDLuOSLLEgz3Qh4iK5jadex14z-i3xJObb5vcjVN326CxdJNzRZo60c9KWY4Nrh7ewziXJv8BQ3x4se62p5paCKdN8quWiG9J5gN4F5dmtZyae0rEhQsy-fy5ugLHPhR97cschr8OnlStVQKRYcUqn7obCnKLNOv-L9a02umsw6ha-G8CSMr3z9QZMfYcPABQAaR3XamUIR_T-ZGiZbpuTDaLfqztCP9jrZ7Q6g4J6SmQtxkcbzj4YdXXcwOr9aUO-07LZuH__tHGXU2bzgsObiClP5Fx13VT0zJzM5rdMtS5OnRwvznIFJUG1VkXXIRG9pVpffOM-kO-FsFW6BTWGi5nBJfi21nLUTh-bNVPB9O8WVfVBl8PwZ2HzjNy0asI_6I2jpweRh8-KNLM5ca18YS1VUS8cgfnc7qFcrnI8kxxDqyITOd2-LMRsngvmJpoJkmKjNIHbnJaoXdvMqFss7YHitJQi7wz3VUKLojK8XdaUc40KQtx7VIdBX9ClDdUFY1kXPxM_c0zLGsLn60a-4PLtUBZEPnBgxZd7-9st9ivBkPXylG9ZNqIe6aD4qxBtp91vI2w18X-MmYT-wb73PcF2IySAuzFk-uqI
            required:
            - content
            - signature
